server:
  port: 8006

spring:
  application:
    name: consul-provide-payment
#consul注册中心
  cloud:
    consul:
      host: 106.52.31.131
      port: 8500
      discovery:
        #hostname: 127.0.0.1
        service-name: ${spring.application.name}
        #开启心跳机制
        heartbeat:
          enabled: true
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动包
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.52.31.131:3306/springcloud_mysql?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: cmzj21

mybatis:
  mapperLocations: classpath:mapper/*.xml
  # 所有Entity别名类所在包
  type-aliases-package: com.cmzj21.springcloud.entities